version: "3.3"
services:

  postgres:
    hostname: postgres
    container_name: postgres
    image: postgres:12
    ports:
      - "5433:5432"
    environment:
      POSTGRES_DB: micro_service_reference_project
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: essentialprogramming
